FROM tomcat:8-jre8
MAINTAINER "Narottam Singh<n.kumar9@yahoo.com>"
ADD Spring_Boot_Mysql_Mongo-0.0.1-SNAPSHOT.jar /home/manikaran/Project/Tools/apache-tomcat-8.0.43/webapps/
EXPOSE 8081
CMD ["catalina.sh", "run"]
