pipeline {
    agent any
    tools {
        maven 'maven' 
    }
    stages {
        stage('Project Cleaning') {
            steps {
                sh 'mvn --version'
                sh 'cd Spring_Boot_Mysql_Mongo && mvn clean'
            }
        } 
     stage('Quality Analysis') {
      parallel {
        stage('Integration Testing') {
          agent any
          steps {
            echo 'Run integration tests here...'
          }
        }  
      stage("SonarQube analysis") {
         steps {
           echo 'SonarQube analysis...' 
          // sh 'cd Spring_Boot_Mysql_Mongo && mvn clean compile sonar:sonar -Dsonar.host.url=http://sonarqube:9000   -Dsonar.login=370c0a2376851662baf405072c1375322bdbe24f'
          }
       }
      }
       }
         stage('Project Building') {
            steps {
                sh 'cd Spring_Boot_Mysql_Mongo && mvn clean install -Dmaven.test.skip=true'
            }
        }
        
      stage('Create Docker') {
      steps {
        echo 'Build and Publish Image...' 
         sh 'docker build -t ${IMAGE} Spring_Boot_Mysql_Mongo'
       
      }
    }
    stage('Deploy Image') {
      steps {
           echo 'Deploy Image...'                                                                                       
      }
    }
        
    }
    
    environment {
    IMAGE = 'db'
    BRANCH_NAME='master'
    //IMAGE = readMavenPom().getArtifactId()
    //VERSION = readMavenPom().getVersion()
    SERVER_MODE = 'dev'
  }
    
    options {
    timestamps()
  }
    
}
