pipeline {
   agent any
   stages {
        stage('Clean') {
            steps {
                  echo 'mvn cleaning...............'
            }
        }
        stage('Build') {
            steps {
                  echo 'maven building...............'
                sh 'mvn -U -B clean install -DPROD_HOME=/home/re50hertz/re-home'
            }
        }
    }
   tools {
    maven 'maven'
    jdk 'Sun Java 8'
  }
  
}
