pipeline {
   agent any
   stages {
        stage('Clean') {
            steps {
                  echo 'maven cleaning...............'
            }
        }
        stage('Build') {
            steps {
                  echo 'maven building...............'
                  sh 'mvn clean'
            }
        }
    }
  
}
