#!/bin/bash
IMAGE_TAG=docker
ENVIRONMENT=dev
HOST_DEPLOY=dev:8081
IMAGE_NAME=$IMAGE_TAG
echo $IMAGE_NAME
echo $HOST_DEPLOY

CONTAINER_NAME=$IMAGE_TAG  
VIRTUAL_HOST_CONFIG="-e VIRTUAL_HOST=$IMAGE_TAG.docker.in"

echo $VIRTUAL_HOST_CONFIG
echo $CONTAINER_NAME

docker -H $HOST_DEPLOY rm -f $CONTAINER_NAME
#docker -H $HOST_DEPLOY pull $IMAGE_NAME

echo "docker run -d --restart=always --name $CONTAINER_NAME -e SPRING_PROFILES_ACTIVE=$ENVIRONMENT $VIRTUAL_HOST_CONFIG $PORT_CONFIG $IMAGE_NAME"
docker run --restart=always  --name $CONTAINER_NAME -e SPRING_PROFILES_ACTIVE=$ENVIRONMENT $VIRTUAL_HOST_CONFIG $PORT_CONFIG $IMAGE_NAME

